### ISSUE TITLE
Add appropriate License

### ISSUE THREAD

**Issue by igeligel** [3YOURMIND/django-migration-linter#1]
Decide for a license since without license this project is not usable.

Probably look into [choosealicense](https://choosealicense.com/).

**Comment by flixx** [comment]
Done

**Comment by igeligel** [comment]
Not added ``Copyright {yyyy} {name of copyright owner}``

**Comment by flixx** [comment]
Mähh,

good catch!
I removed this part from License and added the correct boilerplate to the py files.
