### ISSUE TITLE
Example for "IgnoreMigration()" is gone in doc

### ISSUE THREAD

**Issue by lgylym** [3YOURMIND/django-migration-linter#106]
It looks like the example around usage of `IgnoreMigration()` is gone in doc. Is there any reason for that? Can we have it back?

**Comment by David-Wobrock** [comment]
Good catch! It seems that it went missing when the doc was migrated to multiple files.
https://github.com/3YOURMIND/django-migration-linter/blob/master/docs/usage.md#ignoring-migrations should now contain this doc :)

Thanks for reporting!
