### ISSUE TITLE
Consider not pinning six

### ISSUE THREAD

**Issue by hannseman** [3YOURMIND/django-migration-linter#110]
The latest `six` release is `1.15.0` and a lot of other packages do not pin `six`. This causes conflicts when this package pins it by `six==1.14.0`.

**Comment by David-Wobrock** [comment]
Thanks for reporting! I removed all pinned dependencies, and just define minimal versions.
(basically the same strategy as https://github.com/3YOURMIND/django-migration-linter/issues/108 ;-) )

Hope that works!
