### ISSUE TITLE
django-lint-migrations@2.5.0 fails after update

### ISSUE THREAD

**Issue by sobolevn** [3YOURMIND/django-migration-linter#139]
Traceback:

```
+ python manage.py lintmigrations --exclude-apps=axes --warnings-as-errors
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    main()
  File "manage.py", line 27, in main
    management.execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django_migration_linter/management/commands/lintmigrations.py", line 133, in handle
    config_parser.read(DEFAULT_CONFIG_FILES)
  File "/usr/local/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/lib/python3.8/configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '.editorconfig', line: 3
'root = true\n'
```

CI link: https://github.com/wemake-services/wemake-django-template/pull/1455/checks?check_run_id=1803497890
Reproduction: https://github.com/wemake-services/wemake-django-template/pull/1455

**Comment by David-Wobrock** [comment]
Thanks for all the information!
I'll try to suggest a fix in the next few days (hopefully today) :)

**Comment by skarzi** [comment]
That's because of the [following line](https://github.com/wemake-services/wemake-django-template/blob/54bbcd621e0d49d6c3dbd2c9f532baa59556163e/%7B%7Bcookiecutter.project_name%7D%7D/.editorconfig#L3):

> root = true

It will be nice to log some message on `WARNING` or `ERROR` level instead of raising an exception, but imho the best solution is to load config only from 1 file (e.g. first matched file from [`DEFAULT_CONFIG_FILES`](https://github.com/3YOURMIND/django-migration-linter/blob/bfce31f229714d72524e1bc4ba27b6a9b10c9e55/django_migration_linter/management/commands/lintmigrations.py#L14)). 
It will be also great to have some CLI flag `--config` to set path to the config file - custom one (not included in `DEFAULT_CONFIG_FILES`) or just to avoid loading all files defined in the before-mentioned constant.

**Comment by sobolevn** [comment]
@skarzi just to be clear: this is a valid `.editorconfig` format. https://editorconfig.org/

**Comment by skarzi** [comment]
`.editorconfig` also doesn't seem to be a good place to store the configuration of Django's migration linter, what do you think about removing it from the defaults tuple?

**Comment by David-Wobrock** [comment]
Good point, it doesn't make that much sense to put the config in the editorconfig file :+1:

**Comment by skarzi** [comment]
@David-Wobrock and what do you think about adding an option like `--config config-path` to CLI?

**Comment by David-Wobrock** [comment]
For now, let's remove the `.editorconfig` from the file list.
Adding this option is definitely an option for the next version :)

The Python configparser always expects section headers in the config files, which is not appropriate for editorconfig

**Comment by David-Wobrock** [comment]
> @David-Wobrock and what do you think about adding an option like `--config config-path` to CLI?

I'll let you open an issue for this :)

**Comment by David-Wobrock** [comment]
2.5.1 released, hope everything works as expected now :)

Thanks for the help!

**Comment by sobolevn** [comment]
Yes, it works now! Thanks @David-Wobrock 
https://github.com/wemake-services/wemake-django-template/pull/1462
