### ISSUE TITLE
Current wheel dist installs a "tests" package

### ISSUE THREAD

**Issue by ionelmc** [3YOURMIND/django-migration-linter#147]
It appears that `django_migration_linter-2.5.2-py2.py3-none-any.whl` includes django-migration-linter's tests, which it shouldn't as it would break many things (like my tests).

**Comment by David-Wobrock** [comment]
Hi @ionelmc 
Thanks a lot for submitting the issue!

You are absolutely right, we completely missed the fact that the `find_packages(exclude=["tests/"])` isn't actually excluding the `tests` module :)

Should be easy to fix, I'll hopefully release a new patch version before tonight

**Comment by David-Wobrock** [comment]
Should be fixed with https://pypi.org/project/django-migration-linter/2.5.3/
Tell me if that didn't fix your issue :)
