### ISSUE TITLE
Remove a Foreign key field from a model

### ISSUE THREAD

**Issue by aemitos** [3YOURMIND/django-migration-linter#188]
Hi
We don't know if it's related to the fact that the `deprecate_field` for a foreign key field is not generating a migration for the change (https://github.com/3YOURMIND/django-deprecate-fields/issues/21). 
We couldn't find any steps describing how to remove a foreign key and that's why we open this issue.
We are on Django 3.2.9.
And if we remove the field that it is not being referenced anymore. Generate the migration and run it to remove the field we can see in the database that the field is removed successfully.
We could try to ignore the linter but we wonder if it has a way to make the linter happy. The issue is that we use the linter in our CI/CD and it's failing the builds. It complains about the dropping field operation:

```
❯ ./manage.py makemigrations --check
Migrations for 'our_app':
  our_app/migrations/0110_remove_category.py
    - Remove field category from modelcategory
Linting for 'our_app':
[30-Dec-2021 13:48:04] [INFO/django_migration_linter] [MESSAGE: Calling sqlmigrate command our_app 0110_remove_category]
(our_appa, 0110_remove_category)... ERR
	DROPPING columns (table: ourapp_ourmodel, column: category_id)

The migration linter detected that this migration is not backward compatible.
- If you keep the migration, you will want to fix the issue or ignore the migration.
- By default, the newly created migration file will be deleted.
Do you want to keep the migration? [y/N]
```

**Comment by David-Wobrock** [comment]
Hi @aemitos !

This is one of the cases where I'd recommend to ignore the generated migration (if it only contains the FK column drop).

The linter cannot really know if one is just dropping a column unconsciously or if the column is actually unused.
Therefore => dropping a column raises as a linting error.

So if you are certain that the field is unused (and that during deployment you won't generate errors by dropping the column), you can safely ignore the migration for linting :)
See https://github.com/3YOURMIND/django-migration-linter/blob/main/docs/usage.md#ignoring-migrations that would probably be the easiest way to ignore the migration

It's true that https://github.com/3YOURMIND/django-migration-linter/blob/main/docs/incompatibilities.md#arrow_forward-dropping-a-column is not very explicit about the process there. I'll add some information 👍 

I hope that helps :)
