### ISSUE TITLE
Is the 4.0 version ready for release via pypi?  Are there any major bugs still?

### ISSUE THREAD

**Issue by jessci-aws** [3YOURMIND/django-migration-linter#197]
Would like to use it to get to using Django 4 on an existing project.

Thank you!

**Comment by David-Wobrock** [comment]
Hi @jessci-aws 

Not yet, but soon :) The 4.0 is introducing some breaking changes, so I want to leverage that and breaks designs if necessary.
Once I got time to review in depth all open issues again, we'll move forward and release 4.0 :+1:

**Comment by David-Wobrock** [comment]
Hey @jessci-aws,

We just released 4.0.0 and published it to PyPI :)
See https://github.com/3YOURMIND/django-migration-linter/releases/tag/v4.0.0 and https://pypi.org/project/django-migration-linter/4.0.0/

Let me know if anything isn't working as expected!

(FYI @phillipuniverse)

**Comment by jessci-aws** [comment]
The linter seems to be working fine inside of our project with the new release.

Thank you!!

**Comment by David-Wobrock** [comment]
Awesome, thanks for the feedback @jessci-aws !

Feel free to open an issue if something seems off or could be improved :)
