### ISSUE TITLE
Proper project structure

### ISSUE THREAD

**Issue by igeligel** [3YOURMIND/django-migration-linter#2]
Right now every file is in the root directory. This is not really good.

We should have a proper source folder called `src` or similar and a folder called `tests`.

I would suggest following structure

📁 docs
📁 src
📁 tests
📄 LICENSE
📄 README.md
📄 .gitignore

**Comment by David-Wobrock** [comment]
The project structure should be changed in favor of a PyPi structure, to have it ready for #4 
This means having a setup.py file in the root dir, and put all sources in a directory named after the app. Inside this folder we can then split the files in a src and test folder.
