### ISSUE TITLE
Allow selecting certain warning CODEs as error

### ISSUE THREAD

**Issue by blimmer** [3YOURMIND/django-migration-linter#201]
Today, there's only a single option to change `WARNING`s to `ERROR`s. The `--warnings-as-errors` flag treats all warnings as errors.

It would be nice to selectively opt-in to which `CODE`s you want to treat as errors. I could see using a similar API to `--exclude-migration-tests` where you pass the codes you want to treat as errors.

**Comment by David-Wobrock** [comment]
Hi @blimmer 

Good idea, that makes sense :+1: 
Working it :+1:

**Comment by blimmer** [comment]
This is great, thank you!
