### ISSUE TITLE
Streamline logger adjustments for output

### ISSUE THREAD

**Issue by blueyed** [3YOURMIND/django-migration-linter#207]
The logging library is used for output processing.

For the `lintmigrations` command it gets adjusted here: https://github.com/3YOURMIND/django-migration-linter/blob/8e56562771df63094349fb667bdb06a872462499/django_migration_linter/management/commands/lintmigrations.py#L148-L153

This gets not done with the integration into `makemigrations`: https://github.com/3YOURMIND/django-migration-linter/blob/8e56562771df63094349fb667bdb06a872462499/django_migration_linter/management/commands/makemigrations.py#L47-L90

It would be good if this would behave in the same way, possibly by factoring it out.

It is especially an issue when using something like `logging.basicConfig(level=logging.DEBUG)` in `manage.py`.
It can be fixed by setting the logger's level explicitly, e.g. in Django's `LOGGING` setting, but then the adjustment of the logger based on verbosity would override it.  This might be acceptable, although it should maybe depend on if the logger's level was set explicitly then?

**Comment by David-Wobrock** [comment]
Hi @blueyed 

Thanks for the issue. Yes, we forgot to configure the logger for makemigrations.

I opened https://github.com/3YOURMIND/django-migration-linter/pull/212 let me know if you think this would solve the issue you're describing :)
