### ISSUE TITLE
Allow sqlanalyser to be set in `makemigrations --lint`

### ISSUE THREAD

**Issue by iamstej** [3YOURMIND/django-migration-linter#208]
The ability to provide the SQL Analyser to use when running the migration linter has been implemented for the `lintmigrations` flow; this allows for usage of the library when using unknown database vendors e.g. postgis.

Would it be possible to introduce this into the `makemigrations` flow too? Either via a command argument or to take into consideration the options set in the django settings file.

It currently runs through the `get_sql_analyser_class_from_db_vendor` function which checks for `postgre`.

**Comment by David-Wobrock** [comment]
Hi @iamstej 

Thanks for submitting the issue!
See that should fix this issue and add this feature https://github.com/3YOURMIND/django-migration-linter/pull/214 :)
