### ISSUE TITLE
Integrate to Django through the makemigrations command

### ISSUE THREAD

**Issue by David-Wobrock** [3YOURMIND/django-migration-linter#21]
Improve the linter to integrate directly yo the django makemigrations command.

This way only backward compatible migrations can be generated.

Suggestion of presentation:
```
    makemigrations
    0003_auto_1923423432 ...
    This migration may not be backwards compatible:
    [Show linting errors here]
    You can now edit the migration manually and check again. How do you want to proceed?
    (1) Check again.
    (2) Ignore and proceed.
    (3) Delete migration and abort.
```

One way to integrate it, could be adding the linter to the `INSTALLED_APPS` in the Django settings, and then the `manage.py makemigrations` would get our custom behaviour.

ping FYI @flixx

**Comment by flixx** [comment]
After doing some planning, I think this will only be possible if we would maintain a complete copy of `makemigrations` in this codebase.

@David-Wobrock Do you think that it is worth it?

**Comment by drewbrew** [comment]
Here's a _very_ rough idea (inspired by [Adam's idea](https://adamj.eu/tech/2020/01/13/make-django-tests-always-rebuild-db/) featured in the Django Newsletter that came out this morning):

```python

from django_migration_linter.management.commands.lintmigrations import Command as LintCommand

class Command(BaseCommand):
    def handle(self, *args, **options):
        result = super().handle(*args, **options)
        try:
            LintCommand().handle()
        except SystemExit:
            # offer the delete/ignore option here
            pass
        return result
```

The obvious issue is the disparate set of arguments passed to the linter vs passed to `makemigrations`. Perhaps the linter could use either an rc-file or something in settings.py?

**Comment by David-Wobrock** [comment]
That might work indeed. Thanks for the suggestion @drewbrew 

> The obvious issue is the disparate set of arguments passed to the linter
I guess that we don't have to pass all the arguments to the linter. The goal here would be to override the "makemigrations" command to launch the linter on the new migration and suggest operations.

It would not need all the options that are needed to select or unselect migrations, which reduces a lot the scope of needed options. It would mainly need to the options to select/unselect specific things to lint for 🤔 
If I have the time, I'll try to implement a first version of this logic :)

**Comment by drewbrew** [comment]
Thanks for doing this, @David-Wobrock!

**Comment by David-Wobrock** [comment]
@drewbrew thanks for following the issue :)

It tooks some time to really get into it, but it should work fine now. I'll try to release a new version of the linter with the command in the next days.
Don't hesitate to open an issue if something is not working correctly or could be improved. We can always iterate of the first approach taken :)
