### ISSUE TITLE
support locale  like a ENG, JP, KR

### ISSUE THREAD

**Issue by KimSoungRyoul** [3YOURMIND/django-migration-linter#252]
https://docs.djangoproject.com/en/4.1/topics/i18n/

~~~
# settings.py 

LANGUAGE_CODE = 'ko-KR'

~~~

**Comment by David-Wobrock** [comment]
Hi @KimSoungRyoul

Thanks for opening an issue.

I do not understand the content of the issue though, what do you expect more precisely?
In the meantime, I'll close the issue.
