### ISSUE TITLE
List all checks / violations

### ISSUE THREAD

**Issue by sobolevn** [3YOURMIND/django-migration-linter#43]
It is not quite clear to me what kind of checks are there. 

I would like to have a full list of rules that this linter enforces. 
Thanks! 

Related: https://github.com/wemake-services/wemake-django-template/issues/634

**Comment by David-Wobrock** [comment]
I added some information about what is checked by the linter https://github.com/3YOURMIND/django-migration-linter#backward-incompatible-migrations
