### ISSUE TITLE
Detect if missing merge migration

### ISSUE THREAD

**Issue by David-Wobrock** [3YOURMIND/django-migration-linter#54]

**Comment by mrudelle** [comment]
Django supports this natively via `makemigrations --check --dry-run`

**Comment by David-Wobrock** [comment]
Thank you for your comment @mrudelle. Indeed it does. But it can be interesting for a project to have one command in the CI checking multiple things of the same essence at once. In our case, having a central tool for knowing that your migrations are in a consistent state is part of the goals of the tool :)
