### ISSUE TITLE
Lint only unapplied migrations 

### ISSUE THREAD

**Issue by ambientlight** [3YOURMIND/django-migration-linter#56]
It would great if there is a build-in support for running the linter only on pending migrations, so CI will fail if any pending migrations are non backward compatible

**Comment by ambientlight** [comment]
my temporary solution for this is https://github.com/GeoThings/django-migration-linter/pull/1

**Comment by David-Wobrock** [comment]
Hey @ambientlight , that is a great idea :+1: 
I'll try to integrate this in the first version of the re-write of the linter, so version 1.0.0

The current default behaviour of running the linter will remain the same.
But, how I see it, would be to add an `--lint-unapplied-migrations` or a similar option to run the checking on a subset of migrations.
Maybe we can make it compatible with specifying a commit id
