### ISSUE TITLE
No migrations found when GIT_COMMIT_ID specified

### ISSUE THREAD

**Issue by vladmalynych** [3YOURMIND/django-migration-linter#64]
When GIT_COMMIT_ID option is specified, MigrationLinter executes **diff command on settings directory** with `--relative` parameter sellected:
```
            git_diff_command = (
                "cd {0} && git diff --relative --name-only --diff-filter=AR {1}"
            ).format(self.django_path, git_commit_id)
```
If `settings directory` is not located in the `root directory of the project`, no migrations fill be found.
    
Proposal to use current directory, and run `python manage.py lintmigrations` always from the project root directory.
```
    def handle(self, *args, **options):
>>      current_path = os.getcwd()

        if options["verbosity"] > 1:
            logging.basicConfig(format="%(message)s", level=logging.DEBUG)
        else:
            logging.basicConfig(format="%(message)s")

        linter = MigrationLinter(
>>          current_path,
            ignore_name_contains=options["ignore_name_contains"],
            ignore_name=options["ignore_name"],
            include_apps=options["include_apps"],
            exclude_apps=options["exclude_apps"],
            database=options["database"],
            cache_path=options["cache_path"],
            no_cache=options["no_cache"],
            only_applied_migrations=options["applied_migrations"],
            only_unapplied_migrations=options["unapplied_migrations"],
        )
```
Other sollution: not to use `--relative` option.

**Comment by mrudelle** [comment]
We're running into the same problem. We store settings modules in a separate folder and the `--relative` options does not list files that require using `../`

**Comment by vladmalynych** [comment]
Issue fix is already in progress: https://github.com/3YOURMIND/django-migration-linter/pull/62
