### ISSUE TITLE
Automatically add ignore statements to all affected existing migration files

### ISSUE THREAD

**Issue by lgylym** [3YOURMIND/django-migration-linter#80]
Especially when starting to adopt this tool. It is tedious work to annotate them all.

And I foresee we'll need to do it again if we decide to perform a squashing of existing migrations.

**Comment by David-Wobrock** [comment]
Hi, @lgylym thanks for creating an issue.

If you adopt the linter on an existing project, and you tolerated backward incompatible migrations in the past, you probably want to start linting migrations from a certain version on.

A simple solution might be to add a tag to your code base's version control system (git?) and lint starting from this tag.
This avoids you to change your entire history of migrations.

**Comment by lgylym** [comment]
Hey @David-Wobrock thanks for the reply! Our django app runs inside a docker environment which does not contain git history, so that brings some problem for us.

Would it be a good idea if I introduce another option to the command? Something like `--include-files change-list.txt` to check only the files in the `change-list.txt`? It will certainly be helpful to our CI setup.

**Comment by David-Wobrock** [comment]
Closing, fixed by https://github.com/3YOURMIND/django-migration-linter/pull/81
