### ISSUE TITLE
Option to select what migration states to print

### ISSUE THREAD

**Issue by josh-stableprice** [3YOURMIND/django-migration-linter#82]
For example adding options like `--hide-error` `--hide-ok` `--hide-ignored`
Which would then not show output if any of those states occurred.
I can see the latter two being more useful for development, the second to be more useful for CI and the first one is there for completeness

**Comment by David-Wobrock** [comment]
Hi @josh-stableprice, thanks for submitting an issue!
If this useful, we can definitely add it to the linter. I hope I have enough time this week-end to implement it :)

**Comment by David-Wobrock** [comment]
Actually, is such a granularity necessary? I feel like this would clutter the code quite a lot for not so much value.
What would be easier is to implement a `-v0`, verbosity 0, which does not print anything.
This would mean having 3 levels of verbosity => nothing, the linting message, and a debug level with loads of info.

What do you think @josh-stableprice ? :)

**Comment by josh-stableprice** [comment]
My use case is with lots of migrations where 99% of them are ignored or ok
and one is error. It can be hard to find the erroring one
