### ISSUE TITLE
Linter is not taking altering Colums into account.

### ISSUE THREAD

**Issue by flixx** [3YOURMIND/django-migration-linter#9]
When I create a migration which alters a Field (e.g. from CharField to IntegerField), the migration linter let this migration pass, although it is not backward compatible.

**Comment by David-Wobrock** [comment]
Implementing a basic version of this is straightforward, and will be done soon, but not all field altering is backward incompatible, is it?

I have a doubt on the django behavior here :
* Changing a CharField to IntegerField is obviously incompatible. An old code version will try to insert a string, which is incorrect and rejected (by the database at least). But, is
* Changing an IntegerField to a CharField is backward compatible? How does Django behave here? I guess it depends on how strongly the django ORM is typed. If weakly, it will convert the integer to a string and insert it as a string. But if typed strongly, django should raise an exception. Do you know the correct behavior @flixx ?

**Comment by flixx** [comment]
@David-Wobrock I tested exactly the described case yesterday - indeed **Changing an IntegerField to a CharField** is backward compatible.

However, for the sake of simplicity, I suggest to catch all cases of altering fields. There is still the option to ignore a migration if one is sure that a change is Backwards Compatible.

Maybe it could be included in the error message:

`'err_msg': 'ALTERING column (Could be backward incompatible. You may ignore this migration)'`
