### ISSUE TITLE
Raise backend specific deployment implications

### ISSUE THREAD

**Issue by David-Wobrock** [3YOURMIND/django-migration-linter#99]
For instance, certain operations will potentially lock a table, which can have implications during deployment (lots of operations require the table => we don't acquire the lock waiting to migrate / one we have the lock, long migration, locking the table and making production hang)

https://github.com/yandex/zero-downtime-migrations might be interesting to help out for these warnings

**Comment by timur-orudzhov** [comment]
@David-Wobrock do you have any updates on this?

**Comment by timur-orudzhov** [comment]
@flixx @David-Wobrock If you interested in that feature I could do my best to make it happen. Let me know, please.

**Comment by David-Wobrock** [comment]
Hi @timur-orudzhov 
Thanks for taking interest in that feature :)

The description is halfway up-to-date, since there is already backend specific SQL detection (see https://github.com/3YOURMIND/django-migration-linter/tree/master/django_migration_linter/sql_analyser mostly)

But it would definitely be interesting if the linter could raise issues about potential DB table locks for some operations. I'm mostly familiar with postgresql's behaviour, but I'd be happy to learn more about other databases' behaviours :)

Maybe a good first step would be to list the different cases that we'd like to see raised by the linter 👍 (for the DB you're familiar with maybe, or the one you'd like to implement). 
From there we can see which ones are the easiest to implement and start from there

**Comment by David-Wobrock** [comment]
And the latest update on the issue is that, when I have some time, I'm tackling https://github.com/3YOURMIND/django-migration-linter/issues/121 first and improve the warnings and errors raised for data migrations

**Comment by timur-orudzhov** [comment]
> But it would definitely be interesting if the linter could raise issues about potential DB table locks for some operations.

This is what I'm looking for.

> But it would definitely be interesting if the linter could raise issues about potential DB table locks for some operations. I'm mostly familiar with postgresql's behaviour, but I'd be happy to learn more about other databases' behaviours :)

I also should mention that I look for specific Postgres linter, especially checks that would prevent creating indexes without **concurrent** keyword.

@David-Wobrock what do you think, can we start just for Postgres?

**Comment by timur-orudzhov** [comment]
> Maybe a good first step would be to list the different cases that we'd like to see raised by the linter
good reference, but also specific for Postgres – https://medium.com/braintree-product-technology/postgresql-at-scale-database-schema-changes-without-downtime-20d3749ed680

**Comment by David-Wobrock** [comment]
In https://github.com/3YOURMIND/django-migration-linter/pull/123 I'm starting to run the linter on RunSQL operations, which will make the changes made here even more relevant.

Yes, adding some of those checks only for postgresql is probably a good starting point. We'll need to identify how to detect, if possible from the SQL statement only, if an operation potentially locks a table/will have downtime.
It will probably need to be added in https://github.com/3YOURMIND/django-migration-linter/blob/master/django_migration_linter/sql_analyser/postgresql.py#L5 and define a `migration_test` as defined in the base class https://github.com/3YOURMIND/django-migration-linter/blob/master/django_migration_linter/sql_analyser/base.py#L44

The easiest one is probably adding the check for `CREATE INDEX` which should raise an issue, whereas `CREATE INDEX CONCURRENTLY` shouldn't :)
